#!/bin/bash

# Helper script to get Vercel credentials for GitHub Actions setup

echo "🔑 Vercel Credentials Helper"
echo "============================"
echo ""
echo "This script helps you get the credentials needed for GitHub Actions."
echo ""
echo "📋 You'll need to:"
echo ""
echo "1. VERCEL_TOKEN:"
echo "   → Go to: https://vercel.com/account/tokens"
echo "   → Click 'Create Token'"
echo "   → Name it 'GitHub Actions'"
echo "   → Copy the token"
echo ""
echo "2. VERCEL_ORG_ID:"
echo "   → Go to: https://vercel.com/account"
echo "   → Look for 'Team ID' or 'Organization ID'"
echo "   → Or run: vercel whoami"
echo ""
echo "3. VERCEL_PROJECT_ID:"
echo "   → Go to: https://vercel.com/dashboard"
echo "   → Select your project (client-next)"
echo "   → Go to Settings → General"
echo "   → Copy 'Project ID'"
echo ""
echo "4. Add to GitHub Secrets:"
echo "   → Go to: https://github.com/YOUR_USERNAME/YOUR_REPO/settings/secrets/actions"
echo "   → Click 'New repository secret'"
echo "   → Add each secret:"
echo "     - VERCEL_TOKEN"
echo "     - VERCEL_ORG_ID"
echo "     - VERCEL_PROJECT_ID"
echo "     - BACKEND_API_URL (optional: http://54.196.193.42:8081)"
echo ""
echo "🚀 Quick method using Vercel CLI:"
echo ""
echo "If you have Vercel CLI installed, run:"
echo "  cd client-next"
echo "  vercel link"
echo "  vercel env pull .env.local"
echo ""
echo "This will show your project and org IDs."

